// Signature du document
:sigle: MCED_SGBD_03
:titre: Système de gestion de bases de données
:sous_titre: Rôles et contrôle d’accès
:organisation: CoFELI
:entrepot: CoFELI
:depot: Scriptorum
:branche: v100
:keywords: système de gestion de bases de données, contrôle d’accès, authentification, sécurité
:revnumber: 1.0.0.b
:revdate: 2024-04-01
:version-label: document de travail, ne pas citer
// :author: Christina KHNAISSER
// :email: christina.khnaisser@usherbrooke.ca
:author: Luc LAVOIE
:email: luc.lavoie@usherbrooke.ca

// Contexte de support du document
include::../../../../rep_CoLOED_AsciiDoc.adoc[]
:rep_Scriptorum: {rep_racine}/CoFELI/Scriptorum

// Document bimodal PDF (texte, diaporama) et HTML5 (hypertexte).
// Les attributs format_DIAPO, format_TEXTE et format_HYPER
// permettent de particulariser le document au besoin.

ifndef::format_effectif[:format_effectif: RAPPORT]
ifdef::format_DIAPO[include::{rep_format}/DIAPO_en-tete.adoc[]]
ifndef::format_DIAPO[include::{rep_format}/{format_effectif}_en-tete.adoc[]]

ifndef::format_DIAPO[]
<<<
include::{rep_format}/SOMMAIRE.adoc[]
Introduction aux techniques  de contrôle d’accès.

include::{rep_format}/MISE_EN_GARDE.adoc[]
Le présent document est en cours d’élaboration ;
en conséquence, il est incomplet et peut contenir des erreurs.

include::{rep_format}/HISTO_debut.adoc[]

| 2023-11-01
| LL
| Ébauche initiale selon les formats contenus dans {rep_format}.

include::{rep_format}/HISTO_fin.adoc[]

endif::format_DIAPO[]

<<<
toc::[]

// Corps du document
<<<
[introduction]
== Introduction

La cybersécurité des dépôts de données comportent deux aspects principaux : le contrôle d’accès et l’authentification.

Historiquement les SGBD ont pris en charge ces deux aspects.
Il est désormais jugé préférable de considérer l’authentification comme une responsabilité globale au site (voir à l’organisation).

Le présent document met donc l’accent sur la gestion et le contrôle d’accès.

[NOTE]
Néanmoins, une base suffisante permetant d’intégrer le SGBD à une stucture d’autentification existante est présentée
et des indications minimales sont fournies permettant la prise en charge d’une authentification simple par le SGBD.

ifdef::format_DIAPO[<<<]
== Présentation

Gérer les droits d’accès::
Spécifier la capacité d’un agent à exécuter une action sur un objet.

Contrôler les droits d’accès::
Procéder la vérification du respect de la spécification lors de l’exécution d’une action sur un objet par un agent.

Agent::
utilisateur (_user_), groupe (_user group_)

Action::
opération définie sur une classe d’objets

Objet::
entité contributive à une base de données :
* relation, voire une partie de celle-ci (tuple, attribut) ;
* type, voire une partie de celui-ci (contrainte) ;
* routine ;
* agent, voir des regroupements ou des classes d’agents ;
* ...

ifdef::format_DIAPO[<<<]
== Contrôle d’accès

=== Objets du contrôle d’accès

==== Données

...

* Table
* Tuple(t)
* Attribut

Problématique de la granularité, retour sur la 6FN

==== Routines

...

* Fonctions
* Procédures
* Automatismes

Problématique du double droit (appel et exécution)

==== Types

...

Problématique des domaines de valeurs et des contraintes

==== Structures

...

* Base de données
* Schémas de données

Problématique des politiques

Problématique d’utiliser la bonne structure pour le bon niveau

Problématique des modules (et de leurs interfaces) -> schémas

=== Intermédiaires du contrôle d’accès

==== Agents : Utilisateurs (USER) et Groupes (GROUP)

==== Rôles (ROLE)

Meilleure description du groupe.
Est-il utile de fusionner utilisateur et groupe ?
Quelles en seraient les conséquences ?

=== Droits d’accès

Voir Présentation.

=== Politiques d’accès

Un ensemble de règles prescrivant l’accord des droits d’accès aux agents.
Donc des méta-règles !

ifdef::format_DIAPO[<<<]
== Authentification

[quote, PG, chapitre 21]
--
L’authentification est le processus par lequel le serveur de bases de données
établit l’identité du client et, par extension, détermine si l’application client
(ou l’utilisateur qui l’utilise) est autorisée à se connecter avec le nom d’utilisateur
de bases de données indiqué.
--

ifdef::format_DIAPO[<<<]
== Le cas PostgreSQL

=== Éléments de langage

==== CREATE, DROP

Définir (indéfinir) un rôle et luis associer des droits d’accès

* CREATE ROLE nom [ [ WITH ] Option [ ... ] ]
* DROP ROLE [ IF EXISTS ] nom [, ...]

* Option - de type de rôle (au niveau du SGBD)
  - [NO]SUPERUSER
  - [NO]CREATEDB
  - [NO]CREATEROLE
  - [NO]LOGIN
  - [NO]REPLICATION
  - [NO]BYPASSRLS

* Option - de connexion
  - [ ENCRYPTED ] PASSWORD 'motdepasse' | PASSWORD NULL
  - CONNECTION LIMIT limite_connexion
  - VALID UNTIL 'heuredate'

* Option - de comportement
  - [NO]INHERIT +
    Quand l’instruction GRANT est utilisé pour définir l’appartenance d’un rôle à un autre,
    l’instruction GRANT peut utiliser la clause WITH INHERIT pour indiquer si les droits du
    rôle bénéficiaire doivent être « hérités » par le nouveau membre.
    Si l’instruction GRANT n’indique pas explicitement le comportement de l’héritage,
    l’instruction GRANT sera créée avec WITH INHERIT TRUE si le rôle membre est
    configuré avec INHERIT et avec WITH INHERIT FALSE s’il est configuré avec NOINHERIT. +
    _Avant PostgreSQL 16, l’instruction GRANT n’acceptait pas WITH INHERIT.
    Du coup, modifier la propriété au niveau rôle changerait aussi le comportement
    des droits déjà existants. Ce n’est plus le cas._

  - IN ROLE nom_role [, ...] +
    La clause IN ROLE fait que le nouveau rôle se voit ajouté automatiquement
    comme membre des rôles existants cités. +
    _Il n’existe pas d’option pour ajouter le nouveau rôle en tant qu’administrateur ;
    il faut utiliser une commande GRANT séparée pour cela._

  - ROLE nom_role [, ...] +
    La clause ROLE fait que les rôles existants cités sont ajoutés automatiquement
    comme membre du nouveau rôle. Ceci a pour effet de transformer le nouveau rôle en « groupe ».

  - ADMIN nom_role [, ...] +
    Cette clause est équivalente à la clause ROLE, à la différence que les rôles
    nommés sont ajoutés au nouveau rôle avec l’option WITH ADMIN OPTION.
    Cela leur confère le droit de promouvoir à d’autres rôles l’appartenance à celui-ci.

==== ALTER

Modifier un rôle, en modifier les droits d’accès associés.

* ALTER ROLE nom RENAME TO nouveau_nom
* ALTER ROLE spécification_rôle [ WITH ] Option [ ... ]
* ALTER ROLE spécification_rôle_complet SET paramètre_configuration { TO | = } { value | DEFAULT }
* ALTER ROLE spécification_rôle_complet SET paramètre_configuration FROM CURRENT
* ALTER ROLE spécification_rôle_complet RESET paramètre_configuration
* ALTER ROLE spécification_rôle_complet RESET ALL

où

spécification_rôle_complet ::= +
  { spécification_rôle | ALL } [ IN DATABASE nom_base ]

spécification_rôle ::= +
    nom_rôle
  | CURRENT_ROLE
  | CURRENT_USER
  | SESSION_USER

==== GRANT, REVOKE

.Attribution (retrait) d’un rôle à un autre.

* GRANT nom_role [, ...] TO spécification_rôle [, ...] +
  [ WITH { ADMIN | INHERIT | SET } { OPTION | TRUE | FALSE } ] +
  [ GRANTED BY spécification_rôle ]

où

spécification_rôle ::=
    [ GROUP ] nom_rôle
  | PUBLIC
  | CURRENT_ROLE
  | CURRENT_USER
  | SESSION_USER

.Attribution (retrait) d’un droit d’accès à un rôle

* GRANT droit-accès ON type-d’objet objet [, ...] +
  [ GRANTED BY spécification_rôle ]

où

droit-accès ::=
    SELECT
  | INSERT
  | UPDATE
  | DELETE
  | TRUNCATE
  | REFERENCES
  | TRIGGER
  | CREATE
  | CONNECT
  | TEMPORARY
  | EXECUTE
  | USAGE
  | SET
  | ALTER SYSTEM
  | ...

type-d’objet ::=
    TABLE
  | TYPE
  | ROUTINE
  | ...

[NOTE]
Voir la documentation de PostgreSQL pour déterminer les paires (droit-accès, type-objet) légitimes
et le sens précis du droit en regard du type d’objet.

==== SET

Changement de role.

==== REASSIGN

Tout objet se voit attribué un propriétaire au moment de sa création,
cette instruction permet d’en changer.
Le propriétaire d’un objet hérite automatiquement de certains droits.

==== Les roles prédéfinis

.Questions
// * RLS
* Les politiques ?

=== Authenitification

[quote, PG, chapitre 21]
--
PostgreSQL offre quantité de méthodes d’authentification différentes.
La méthode utilisée pour authentifier une connexion client particulière
peut être sélectionnée d’après l’adresse (du client), la base de données
et l’utilisateur.

Les noms d’utilisateur de bases de données sont séparés de façon logique des
noms d’utilisateur du système d’exploitation sur lequel tourne le serveur.
Si tous les utilisateurs d’un serveur donné ont aussi des comptes sur la
machine serveur, il peut être pertinent d’attribuer aux utilisateurs de bases
de données des noms qui correspondent à ceux des utilisateurs du système d’exploitation.
Cependant, un serveur qui accepte des connexions distantes peut avoir des
utilisateurs de bases de données dépourvus de compte correspondant sur
le système d’exploitation. Dans ce cas, aucune correspondance entre
les noms n’est nécessaire.
--

[quote, LL, 2024-04-01]
--
PostgreSQL offre quantité de méthodes d’authentification différentes.
La méthode utilisée pour authentifier *le client associé à une connexion* particulière
peut être sélectionnée d’après l’adresse *d’origine de la connexion*, la base de données
et le *nom d’utilisateur associé à la connexion*.
--

ifdef::format_DIAPO[<<<]
== Le cas Oracle

...

ifdef::format_DIAPO[<<<]
== Le cas MS-SQL

...

<<<
[conclusion]
== Conclusion

<<<
[references]
== Références
PG::
https://docs.postgresql.fr/16/client-authentication.html (2023-11-10)

<<<
[glosssary]
== Glossaire

----
Sources consultées en juin et juillet 2023

* Antidote : Antidote 11 v4.2 (2023), voir https://www.antidote.info
* Larousse : https://www.larousse.fr/dictionnaires/francais
* Le Robert : https://dictionnaire.lerobert.com
* Wikipédia : https://fr.wikipedia.org/wiki
----

include::{rep_Scriptorum}/doc/_glo/ACID.adoc[]
include::{rep_Scriptorum}/doc/_glo/base_de_données.adoc[]
include::{rep_Scriptorum}/doc/_glo/programme__f.adoc[]
include::{rep_Scriptorum}/doc/_glo/SGBD.adoc[]
include::{rep_Scriptorum}/doc/_glo/SGBDR.adoc[]
include::{rep_Scriptorum}/doc/_glo/SQL.adoc[]

ifdef::format_DIAPO[include::{rep_format}/DIAPO_en-pied.adoc[]]
ifndef::format_DIAPO[include::{rep_format}/{format_effectif}_en-pied.adoc[]]
